##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: authentication
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
  r2dbc:
    host: 172.21.53.181
    port: 5432
    database: authentication
    schema: public
    username: admin_db
    password: 960311
    sql:
      init:
        mode: always